### ISSUE TITLE
Should add custom DTB support for the Variscite DART-MX8M device family

### ISSUE THREAD

**Issue by cywang117** [balena-io/open-balena-api#1033]
Perhaps done by adding to `src/features/vars-schema/env-vars.ts` : https://github.com/balena-io/open-balena-api/commit/581db9e845cfd15eae5f2caa000a8e4dbb24b392#

**Comment by atlantis** [comment]
This would allow us to use a custom device tree for our project without having to manually install it on each unit with a somewhat hacky script... thanks!

**Comment by acostach** [comment]
Hi @atlantis, do you need this for the imx8m-var-dart or the imx8mm-var-dart ?

**Comment by atlantis** [comment]
The imx8mm-var-dart please!

Thanks!

**Comment by alexgg** [comment]
There is an OS improvement related to this at https://jel.ly.fish/improvement-device-tree-variants-support-5a147be (internal)
