### ISSUE TITLE
Version 1 and 2 of open-balena-api

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/open-balena-api#1054]
Hi all,

I'm in the middle of creating a new upgrade for openBalena to the newest versions, and the last weeks I've seen many dependency updates. However, I now see in the changelog that version 1 and version 2 are created.

Is this on purpose or are there some issues with versioning at the moment?
In other words, what's the latest version I should use, version 2.0.0 or version 0.209.2?

Thanks in advance!

**P.S.** 
I don't really know where to ask such questions, didn't think the forum was the best place, but "Discussions" aren't available in this repo. Happy to ask these kind of questions on the forum, but let me know what's the best place!

**Comment by thgreasi** [comment]
Hi @bartversluijs ,
If you were planning to use v0.209.x then it's fine & preferable to use v2.0.0, which as of writing this now the latest version.
The two major bumps happened by accident w/o us realizing, after we integrated renovatebot and I approved two devDepenency bumping PRs that were incorrectly marked as major w/o noticing.
That being said, versions v0.209.2, v1.0.0 & v2.0.0 should generate the exact same compiled output and runtime behavior.

I'm sorry for the confusion :(
