### ISSUE TITLE
Should not retry to fetch device types for ever

### ISSUE THREAD

**Issue by thgreasi** [balena-io/open-balena-api#16]
If something goes wrong with the s3 device types we currently recursively try to refetch them.
Chaining all those promises increasingly consumes more and more memory.
We should fail with an error after a few retries since the http requests would have timeout anyway.

**Comment by dfunckt** [comment]
Device type fetching has changed significantly and this is no longer really relevant.

**Comment by thgreasi** [comment]
Thanks for spotting this!
