### ISSUE TITLE
v19.1.19 Error: Cannot find module '/usr/src/app/init.js' imported from /usr/src/app/index.js

### ISSUE THREAD

**Issue by jenish1231** [balena-io/open-balena-api#1612]
![image](https://github.com/balena-io/open-balena-api/assets/19236975/5f876b47-44e9-4e81-8158-3dd4a172e7af)

**Comment by thgreasi** [comment]
Hi,
Did you have chance to narrow this down to which version this first started happening?

Kind regards,
Thodoris

**Comment by thgreasi** [comment]
Can you also clarify whether you are trying to run the Docker image or trying to import the open-balena-api as a node module?

**Comment by jenish1231** [comment]
@thgreasi I tried to use it as a Docker image. Setting `PRODUCTION_MODE: true` solved the problem. Thank you for your quick response.

**Comment by thgreasi** [comment]
Hi @jenish1231 PR #1618 should allow you to run open-balena-api even without the `PRODUCTION_MODE: true` variable.
