### ISSUE TITLE
Increase max app name length from 30 to 32 chars

### ISSUE THREAD

**Issue by foobarto** [balena-io/open-balena-api#224]
As title suggest, please consider increasing max application name length from 30 to 32 to allow names based on 256bit values (ie. UUID or AES256 hash).

This would be very useful when using openBalena as a component of a bigger system where the name could be generated and used as a reference. Since the name has to be unique anyway.

**Comment by dfunckt** [comment]
Fixed in #425 -- will be available in the next openBalena release.
