### ISSUE TITLE
Unable to remove an application

### ISSUE THREAD

**Issue by richbayliss** [balena-io/open-balena-api#32]
From the CLI:

`$ balena app rm myApp`

Yields the following...

`BalenaRequestError: Request error: Error deleting resource 'release_tag' before deleting 'release'`

**Comment by richardlevano** [comment]
I have exactly the same problem.
Using balena-cli v9.4.0
balena app rm myApp
Are you sure you want to delete the application? Yes
BalenaRequestError: Request error: Error deleting resource 'release_tag' before deleting 'release'

**Comment by dfunckt** [comment]
This should be fixed by #33
