### ISSUE TITLE
The API should set a supervisor_release in the state endpoint when it's null

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/open-balena-api#321]
We are aiming to make it so that all devices have an assigned supervisor_release field. To do this we should use the supervisor version in the state endpoint and find the correct supervisor_release based on that version, and set that in the device resource.

**Comment by xginn8** [comment]
We will now set the `should_be_managed_by__supervisor_release` value upon provision for new devices corresponding to what the device is running already. This is now deployed in production.
