### ISSUE TITLE
Malformed URL error with CURL request from API

### ISSUE THREAD

**Issue by panbanda** [balena-io/open-balena-api#717]
I am trying to update an environment variable (create works fine).  When I follow the v6 docs I get a malformed error.  I am using the latest release `v3.2.2` of open balena.

https://www.balena.io/docs/reference/api/resources/device_environment_variable/

```sh
curl -X PATCH "https://api.APIURL/v6/device_environment_variable/14" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer XXXXXXXXX" \
--data '{"value": "what"}'
```

### Result 

"Malformed url: '/resin/device_environment_variable/14'"

**Comment by dfunckt** [comment]
You’re almost there, except you need to use parentheses to refer to a specific ID: `device_environment_variable(14)`

**Comment by panbanda** [comment]
AH, I see. I thought it was an optional parameter (from traditional documentation) and was wondering why it excluded the slash.

Not gonna lie, big learning curve for this api :D but very appreciative for the platform.
