### ISSUE TITLE
Add Loki envs to confd

### ISSUE THREAD

**Issue by robbe-haesendonck** [balena-io/open-balena-api#870]
Currently we are exploring the options of shipping all device logs to a central place, as I was exploring the source code I found a few references to Loki.

To enable this functionality and allow everyone to use it, the env variables should be exposed by adding them to conf.d

**Comment by codewithcheese** [comment]
hi @robbe-haesendonck I am one of the authors of the `LokiBackend`. To provide some context; the goal was to replace Redis with Loki, for logs storage and retrieval, and eventually provide more advanced log search features. However, this project was not completed. Currently, if you set a value for those envvars logs will be written to both Redis and Loki. To view the logs from Loki you will need to use the Loki API directly or a separate tool such as Grafana.

**Comment by robbe-haesendonck** [comment]
Hello @codewithcheese 

We are currently in the progress of deploying openbalena to production, now we need a good log shipping solution, thus we found the LokiBackend. Are there any plans to complete the LokiBackend? I think providing a way to enable it (feature complete or not) for Loki would be good. As currently monitoring/log viewing can only be done in the balena cli, and there is no good way to integrate with some more advanced monitoring/logging systems.

**Comment by codewithcheese** [comment]
@robbe-haesendonck a better log experience is still something we would love to offer, but no one is working on it at the moment. We have discussed your PR internally and are happy to accept that, I think @dfunckt was going to do that sometime today. Keep in mind its an unreleased feature, so we cannot make any guarantees around it not being broken or removed in future versions.

An alternative that most users use is to have a log agent service on each device, sending logs directly to your log aggregation host.

**Comment by robbe-haesendonck** [comment]
Thanks for the response @codewithcheese

We will probably be running a prometheus agent on every device for metrics. Tried to port the baletheus example to openbalena but that still needs a tunneler. The thing with the log agent service raises some questions for me is how is outgoing connectivity done with openbalena, does everything run over the VPN or only management related traffic?

All in all Loki worked pretty well when I tested it and would allow us to easily integrate in already existing tooling we have, the fact that it could fail/is untested does not matter that much as logs are also still available in Redis/via the cli, the thing with those 2 is that they aren't easily ship-able as far as I can tell.

**Comment by dfunckt** [comment]
> The thing with the log agent service raises some questions for me is how is outgoing connectivity done with openbalena, does everything run over the VPN or only management related traffic?

There is no outgoing traffic (from the perspective of a device) via the VPN, only inbound for SSH and notification support after significant events the device would benefit from reacting to immediately (like reboot, update, etc.).
